"""Data quality filters for code preprocessing.

Implements filtering heuristics to remove low-quality, auto-generated,
or non-code files from The Stack v2 before tokenization. These filters
are critical for training quality — garbage in, garbage out.

Filters applied:
  1. File size: Remove tiny (<100 bytes) and huge (>100KB) files
  2. Line statistics: Remove files with extremely long lines
  3. Non-ASCII ratio: Remove files that are mostly binary/encoded
  4. Auto-generated detection: Remove build artifacts, configs, etc.
  5. Language filtering: Keep only target programming languages
"""

import re
from typing import Dict, List, Optional, Set


# ── Target Languages and Weights ────────────────────────────────────

LANGUAGE_WEIGHTS: Dict[str, float] = {
    "python": 0.25,
    "javascript": 0.10,
    "typescript": 0.10,
    "java": 0.10,
    "c": 0.05,
    "c++": 0.05,
    "go": 0.08,
    "rust": 0.07,
    "shell": 0.05,
    "sql": 0.05,
    "ruby": 0.02,
    "php": 0.02,
    "scala": 0.02,
    "kotlin": 0.02,
    "swift": 0.02,
}

TARGET_LANGUAGES: Set[str] = set(LANGUAGE_WEIGHTS.keys())


# ── Auto-generated file indicators ─────────────────────────────────

AUTO_GENERATED_PATTERNS = [
    re.compile(r"auto[-\s]?generated", re.IGNORECASE),
    re.compile(r"do not edit", re.IGNORECASE),
    re.compile(r"generated by", re.IGNORECASE),
    re.compile(r"this file is generated", re.IGNORECASE),
    re.compile(r"machine[-\s]?generated", re.IGNORECASE),
    re.compile(r"automatically generated", re.IGNORECASE),
]

# Files to skip based on name patterns
SKIP_FILENAME_PATTERNS = [
    re.compile(r"\.min\.(js|css)$"),          # Minified files
    re.compile(r"\.bundle\.(js|css)$"),        # Bundled files
    re.compile(r"package-lock\.json$"),         # Lock files
    re.compile(r"yarn\.lock$"),
    re.compile(r"\.map$"),                      # Source maps
    re.compile(r"\.pb\.go$"),                   # Protobuf generated
    re.compile(r"_pb2\.py$"),                   # Protobuf generated
    re.compile(r"\.generated\.\w+$"),           # Generic generated
    re.compile(r"vendor/", re.IGNORECASE),      # Vendored dependencies
    re.compile(r"node_modules/", re.IGNORECASE),
    re.compile(r"__pycache__/"),
]


# ── Filter Functions ────────────────────────────────────────────────


def filter_by_size(content: str, min_bytes: int = 100, max_bytes: int = 100_000) -> bool:
    """Check if file content is within acceptable size range.

    Args:
        content: File content string.
        min_bytes: Minimum content length in bytes.
        max_bytes: Maximum content length in bytes.

    Returns:
        True if content passes the filter.
    """
    content_bytes = len(content.encode("utf-8", errors="replace"))
    return min_bytes <= content_bytes <= max_bytes


def filter_by_line_stats(
    content: str,
    max_line_length: int = 1000,
    max_avg_line_length: int = 200,
    min_lines: int = 3,
) -> bool:
    """Check line-level statistics for code quality.

    Removes files with extremely long lines (likely data/minified),
    very high average line length, or too few lines.

    Args:
        content: File content string.
        max_line_length: Maximum allowed single line length.
        max_avg_line_length: Maximum average line length.
        min_lines: Minimum number of lines.

    Returns:
        True if content passes the filter.
    """
    lines = content.split("\n")
    num_lines = len(lines)

    if num_lines < min_lines:
        return False

    # Check for extremely long lines (data files, minified code)
    max_len = max(len(line) for line in lines)
    if max_len > max_line_length:
        return False

    # Check average line length
    avg_len = sum(len(line) for line in lines) / num_lines
    if avg_len > max_avg_line_length:
        return False

    return True


def filter_by_ascii_ratio(content: str, min_ascii_ratio: float = 0.80) -> bool:
    """Check that the content is mostly ASCII (i.e., actual code).

    Files with low ASCII ratio are likely binary, encoded data,
    or non-Latin documentation.

    Args:
        content: File content string.
        min_ascii_ratio: Minimum fraction of ASCII characters.

    Returns:
        True if content passes the filter.
    """
    if not content:
        return False

    ascii_count = sum(1 for c in content if ord(c) < 128)
    ratio = ascii_count / len(content)
    return ratio >= min_ascii_ratio


def filter_auto_generated(content: str, check_lines: int = 5) -> bool:
    """Check if the file appears to be auto-generated.

    Looks for auto-generation markers in the first few lines of the file.

    Args:
        content: File content string.
        check_lines: Number of initial lines to inspect.

    Returns:
        True if the file is NOT auto-generated (passes the filter).
    """
    # Check first N lines for auto-generated markers
    header = "\n".join(content.split("\n")[:check_lines])

    for pattern in AUTO_GENERATED_PATTERNS:
        if pattern.search(header):
            return False

    return True


def filter_by_filename(filename: Optional[str]) -> bool:
    """Check if the filename indicates a file to skip.

    Args:
        filename: File path/name string.

    Returns:
        True if the file should be KEPT (passes the filter).
    """
    if filename is None:
        return True

    for pattern in SKIP_FILENAME_PATTERNS:
        if pattern.search(filename):
            return False

    return True


def filter_by_language(language: str) -> bool:
    """Check if the programming language is in our target set.

    Args:
        language: Programming language string (e.g., "python").

    Returns:
        True if the language is a target language.
    """
    return language.lower() in TARGET_LANGUAGES


def apply_all_filters(
    content: str,
    language: str,
    filename: Optional[str] = None,
) -> bool:
    """Apply all quality filters to a code sample.

    Args:
        content: File content string.
        language: Programming language.
        filename: Optional file path.

    Returns:
        True if the sample passes ALL filters.
    """
    if not filter_by_language(language):
        return False

    if not filter_by_filename(filename):
        return False

    if not filter_by_size(content):
        return False

    if not filter_by_ascii_ratio(content):
        return False

    if not filter_by_line_stats(content):
        return False

    if not filter_auto_generated(content):
        return False

    return True


def get_language_weight(language: str) -> float:
    """Get the sampling weight for a programming language.

    Languages with higher weights will be sampled more frequently
    during training to achieve the target language distribution.

    Args:
        language: Programming language string.

    Returns:
        Sampling weight (0.0 if language not in target set).
    """
    return LANGUAGE_WEIGHTS.get(language.lower(), 0.0)
